### ISSUE TITLE
Information about part of code

### ISSUE THREAD

**Issue by MegaManSec** [yuichiro-naito/asmctl#16]
Hi there,

I am trying to understand where this line is from: https://github.com/yuichiro-naito/asmctl/blob/46d5815753a741b02563bb416554734b84c74c42/src/asmctl.c#L370

```c
	memcpy(v,&buf[2],n*sizeof(int));

	num_of_video_levels=n;
	video_levels=v;


    /* if conf_file is empty or not created,
       use default value */
	if (video_economy_level < 0) {
		video_economy_level = n > 3 ? v[3] : v[n];
	}
	if (video_fullpower_level < 0) {
		video_fullpower_level = n > 3 ? v[3] : v[n];
	}
```

I am trying to understand why the default value is `v[3]`? My understanding is that `hw.acpi.video.lcd0.levels` is retrieved, and then the first two values are skipped (because `memcpy` begins at `&buf[2]`).

I do not have a system which can actually use that sysctl, but from what I have seen, it would look like this:
`hw.acpi.video.lcd0.levels: 80 50 0 1 2 ....` -- Therefore `v[3]` is going to be "2".

Is there any reason for this?

Thank you

**Comment by yuichiro-naito** [comment]
Yes, your guess is right.
The actual sysctl values of my Macbook Air 2012 are as follows.

`hw.acpi.video.lcd0.levels: 80 47 0 7 13 20 27 33 40 47 53 60 67 73 80 87 93 100`

I set the default value from v[0] at first to write the code. While I'm testing, it blackouts my screen when I invoke asmctl for the first time. I was so bothered by recovering the brightness.

I changed a little bit bright value taken from v[3]. I'm not sure number of brightness values the other systems have. I chose a small but bigger than 0 and the brightness value so that users can see the display. I thought 3 was reasonable.

**Comment by MegaManSec** [comment]
> it blackouts my screen when I invoke asmctl for the first time

Sure, that's because v[0] corresponds to levels[2] which is 0. Doesn't levels[0] correspond to the current fullpower brightness and levels[1] correspond to the current economy brightness? Shouldn't they be used by default instead?

By the way, according to https://forums.freebsd.org/threads/turn-off-display-when-lid-is-closed.57292/#post-326790 the order of the levels is not always increasing so up/down may be reversed for some screens. Maybe we should sequentially order the levels after they're retrieved to fix that case. 


Also according to https://forums.freebsd.org/threads/freaking-brightness-and-freebsd-man-panges-not-working.73636/#post-449589 the levels can contain even 102 entries so Asmctl is currently truncating the results quite a lot here: https://github.com/yuichiro-naito/asmctl/blob/46d5815753a741b02563bb416554734b84c74c42/src/asmctl.c#L342

**Comment by MegaManSec** [comment]
Yeah, according to the source at https://github.com/freebsd/freebsd-src/blob/bf085659dac9dd32259d05311a0a78d068fd59ef/sys/dev/acpica/acpi_video.c#L714 the fullpower and economy levels should be the first and second values respectively. I will add a commit to #17 to fix this.
